### ISSUE TITLE
Gem Dependencies in README

### ISSUE THREAD

**Issue by hanynowsky** [sensu-plugins/sensu-plugins-xmpp#1]
Hello,
I think gem dependencies (xmpp4r) should be mentioned in the README:

```
/opt/sensu/embedded/bin/gem install xmpp4r --no-ri --no-rdoc
Successfully installed xmpp4r-0.5.6
1 gem installed

```

---
- typo: _room_password_ not _room_passord_

**Comment by mattyjones** [comment]
@hanynowsky  If it is needed then we should add it to the gem dependencies

**Comment by eheydrick** [comment]
xmpp4r is a runtime dependency and would be installed along with the plugin. I fixed that typo in the README.

**Comment by hanynowsky** [comment]
Thanks. That plugin rocks.
