### ISSUE TITLE
Update sensu-plugin conservative dep 3.0 to pick up new Sensu Go event data mapping

### ISSUE THREAD

**Issue by jspaleta** [sensu-plugins/sensu-plugins-xmpp#6]
sensu-plugin 2.7 has new logic to aid mutators and handlers map sensu Go event data into sensu 1.x event data. When updating need to use conservative dep so that 2.7.x patch releases will satisfy runtime dependency.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-xmpp/versions/3.0.0
closed via #12
